---
- name: Set OpenVSwitch packages
  tags: openvswitch
  set_fact:
    openVSwitchPackages:
        openvswitch-switch

- name: Install OpenVSwitch software
  tags: openvswitch
  apt:
    name: "{{ openVSwitchPackages }}"

- name: Create OpenVSwitch bridges
  tags: openvswitch
  openvswitch_bridge:
    bridge: "{{ item.bridge }}"
    state: present
  loop: "{{ openVSwitchConfig }}"

- name: Add port to OpenVSwitch bridges 
  tags: openvswitch
  openvswitch_port:
    bridge: "{{ item.0.bridge }}"
    port: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ openVSwitchConfig }}"
    - port

- name: Add VLANs to OpenVSwitch bridges 
  tags: openvswitch
  openvswitch_bridge:
    bridge: "VLAN{{ item.1 }}"
    parent: "{{ item.0.bridge }}"
    vlan: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ openVSwitchConfig }}"
    - vlan

- name: Configure netplan interfaces for OpenSwitch
  tags: openvswitch, test
  template:
    src: interfaces.yaml
    dest: "/etc/netplan/{{ item.1 }}.yaml"
    owner: root
    group: root
    mode: "0644"
  with_subelements:
    - "{{ openVSwitchConfig }}"
    - port

